version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: nexapay
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  nexapay-bank-backend:
    build: ./nexapay-bank-backend
    image: bank-backend-image
    container_name: bank-backend-container
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-container:3306/nexapay
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root1234
      - USER_ACCOUNT_API_URL=http://user-backend-container:8081
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8082:8082"

  nexapay-user-backend:
    build: ./nexapay-user-backend
    image: user-backend-image
    container_name: user-backend-container
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-container:3306/nexapay
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root1234
      - BANK_API_URL=http://bank-backend-container:8082
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8081:8081"

  nexapay-frontend:
    build: ./nexapay-frontend
    image: frontend-image
    container_name: frontend-container
    command: npm run dev
    environment:
      NODE_ENV: development
      VITE_API_USER_AND_ACCOUNT_API_URL: http://localhost:8081
      VITE_API_BANK_API_URL: http://localhost:8082
    depends_on:
      - mysql
      - nexapay-bank-backend
      - nexapay-user-backend
    networks:
      - app-network
    ports:
      - 5173:5173

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: