version: '3'
services:
  nexapay-bank-backend:
    build: ./nexapay-bank-backend
    image: bank-backend-image
    container_name: bank-backend-container
    environment:
      - DATABASE_URL=jdbc:mysql://nexpay-mysql-nexapay.l.aivencloud.com:11021/nexapay
      - DATASOURCE_USERNAME=avnadmin
      - DATASOURCE_PASSWORD=AVNS_pSZZmJnaOAxQKEwedTz
      - USER_ACCOUNT_API_URL=http://user-backend-container:8081
    networks:
      - app-network
    ports:
      - "8082:8082"

  nexapay-user-backend:
    build: ./nexapay-user-backend
    image: user-backend-image
    container_name: user-backend-container
    environment:
      - DATABASE_URL=jdbc:mysql://nexpay-mysql-nexapay.l.aivencloud.com:11021/nexapay
      - DATASOURCE_USERNAME=avnadmin
      - DATASOURCE_PASSWORD=AVNS_pSZZmJnaOAxQKEwedTz
      - BANK_API_URL=http://bank-backend-container:8082
    networks:
      - app-network
    ports:
      - "8081:8081"

  nexapay-frontend:
    build: ./nexapay-frontend
    image: frontend-image
    container_name: frontend-container
    command: npm run dev
    environment:
      NODE_ENV: development
      VITE_API_USER_AND_ACCOUNT_API_URL: https://user-backend-image.onrender.com
      VITE_API_BANK_API_URL: https://bank-backend-image.onrender.com
    depends_on:
      - nexapay-bank-backend
      - nexapay-user-backend
    networks:
      - app-network
    ports:
      - "5173:5173"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: